### ISSUE TITLE
std::false_type in safe_base constructor

### ISSUE THREAD

**Issue by akrzemi1** [robertramey/safe_numerics#24]
`safe_base` has a constructor taking `std::false_type` as second argument:

```c++
constexpr explicit safe_base(const Stored & rhs, std::false_type);
```

There is no argument taking the corresponding `std::true_type`. It looks like the purpose of this constructor is to initialize the value but skip the validation. Maybe, in order to make the intention more clear to whoever reads the code, invent your own empty class, like `skip_validation`, and use it instead?

**Comment by robertramey** [comment]
done
