### ISSUE TITLE
Consider using BOOST_[UN]LIKELY in conditional branches

### ISSUE THREAD

**Issue by badair** [robertramey/safe_numerics#36]
... In both conditional operators and if/else blocks. This can yield better code generation on some platforms.

http://www.boost.org/doc/libs/1_63_0/libs/config/doc/html/boost_config/boost_macro_reference.html
http://stackoverflow.com/questions/15468042/how-far-does-gccs-builtin-expect-go

**Comment by robertramey** [comment]
I would be extremely unlikely to complicate code even further by including this information.  If I were to actually profile the code I might change my mind but I sort of doubt it.  So I'm going to close this.  I'll add to a list of pending ideas/enhancements.
