### ISSUE TITLE
Problems with Type Requirements 

### ISSUE THREAD

**Issue by akrzemi1** [robertramey/safe_numerics#46]
In the current implementation `safe<T>` will only work with `T` being a C++ scalar type. Therefore making a general type requirements that say what operations are allowed is superfluous, and confusing (because it implies that `safe<>` is more generic.

You do not need a concept to constrain anything with it, in your library. Or is the purpose of the Type requirements to show in detail what it means that `safe<T>` is a 'drop-in replacement for `T`?

If you want to extend `safe<T>` for other integer types, Type requirement still need to be fixed:

1. Is it really necessary that `T` can be written into a stream?
2. In implementation you use literals -1, 0, 1 directly. Document that any T must be convertible and comparable with these literal values, or use them indirectly via overloadable traits: `Integral<T>::zero()`, `Integral<T>::one()`.
3. Do you require that T is default-constructible? If so, do you require that thus constructed object has numeric value 0?

**Comment by robertramey** [comment]
OK - updated all the docs to addresss all of this - check in soon !!!
