### ISSUE TITLE
fail to compile on signed vs. unsigned comparison

### ISSUE THREAD

**Issue by akrzemi1** [robertramey/safe_numerics#47]
This is just a suggestion.
Currently the following returns true: 

```
safe<signed>{-1} < safe<unsigned>{1}
```

Which is quite clever a fix, but maybe instead, this should fail to compile, and therefore force the user to rethink the comparison and do one of the following:

1. Change the signed-ness of one of the types
2. Use a named function for comparison.

**Comment by robertramey** [comment]
I went through and more carefully follow the language / procedures of the standard.

The standard considers < (and other operators) binary operators.
In such case, promotion rules are invoked to promote both operands to the same type.
then the types are converted.

depending on the size of the two operands, the promotion may result in an (undetected) error.  This can occur when a negative value is promoted to an unsigned value - which can happen.  On cases like this, errors injected during promotions are caught as errors.  This means that we aren't changing C++/C behavior, we are just trapping the places where it occurs.  This is in the spirit of the library.
