### ISSUE TITLE
Error in static_assert in safe_base::operator~() (bitwise not)

### ISSUE THREAD

**Issue by nmusolino** [robertramey/safe_numerics#49]
[This static_assert](https://github.com/robertramey/safe_numerics/blob/master/include/safe_base.hpp#L261) is missing a `!`.  The intent of the static assert is to confirm the Stored type is unsigned.

    constexpr safe_base operator~() const {
        static_assert(
            std::numeric_limits<Stored>::is_signed,
            "Bitwise inversion of signed value is an error"
        );
        return ~(m_t);
    }

I actually was going to submit a pull request but got surprising runtime behavior.  I will detail this in a separate issue.

**Comment by robertramey** [comment]
I think I've addressed this.
