### ISSUE TITLE
Documentation errors regarding SafeInt

### ISSUE THREAD

**Issue by dcleblanc** [robertramey/safe_numerics#55]
SafeInt isn't currently a Boost library, which is why it doesn't use Boost conventions. It doesn't have any dependency on Boost.

SafeInt does not require porting for different compilers, is fully supported on gcc, clang, and Visual Studio, and has been since 2009, with improvements made in this area in 2014.

The license has been changed from MS-PL to MIT license (very recent change).

The library has had a test suite since before it was public, and is now located here:
https://github.com/dcleblanc/SafeInt/Test

SafeInt also has no external dependencies other than standard library files, and doesn't need anything else installed to work.

I appreciate the attribution, but let's ensure that the documentation is correct, and current.

**Comment by robertramey** [comment]
Hmmm - I think "documentation errors" is a little snarky.  But never-the-less, I've added the information about to the documentation.

**Comment by dcleblanc** [comment]
Thanks!

**Comment by dcleblanc** [comment]
Wasn’t meant to be snarky, sorry if it was taken that way. Thanks for fixing these inaccurate comments.
